Shopify/protoboeuf

- lib/protoboeuf/codegen.rb
Since Field#wire_type covers the enum case too
> Remove unneeded wire_type method in CodeGen

- lib/protoboeuf/codegen.rb
- lib/protoboeuf/protobuf/boolvalue.rb
- lib/protoboeuf/protobuf/bytesvalue.rb
- lib/protoboeuf/protobuf/doublevalue.rb
- lib/protoboeuf/protobuf/floatvalue.rb
- lib/protoboeuf/protobuf/int32value.rb
- lib/protoboeuf/protobuf/int64value.rb
- lib/protoboeuf/protobuf/stringvalue.rb
- lib/protoboeuf/protobuf/timestamp.rb
- lib/protoboeuf/protobuf/uint32value.rb
- lib/protoboeuf/protobuf/uint64value.rb
- test/fixtures/typed_test.correct.rb
Alternative to #106 
Also reduces allocations by half.
Still gets to use `opt_newarray_send`.
```
before
TOTAL    (pct)     SAMPLES    (pct)     FRAME
103572  (95.0%)      103572  (95.0%)     Upstream::TrunkItem#_encode
108505  (99.5%)        4933   (4.5%)     Upstream::Vehicle#_encode
108977 (100.0%)         465   (0.4%)     Upstream::ParkingFloor#_encode
108993 (100.0%)          14   (0.0%)     Upstream::ParkingLot.encode
108511  (99.5%)           6   (0.0%)     Upstream::ParkingSpace#_encode
after
TOTAL    (pct)     SAMPLES    (pct)     FRAME
51786  (95.0%)       51786  (95.0%)     Upstream::TrunkItem#_encode
54253  (99.5%)        2467   (4.5%)     Upstream::Vehicle#_encode
54494  (99.9%)         234   (0.4%)     Upstream::ParkingFloor#_encode
11   (0.0%)          11   (0.0%) …
```
> Set frozen_string_literal: true on generated files

- lib/protoboeuf/codegen.rb
- lib/protoboeuf/protobuf/doublevalue.rb
- lib/protoboeuf/protobuf/floatvalue.rb
The format spec is clear that floats are little-endian, but we were
using the directives that use the host's endianess (which could be
big-endian).
> Use little-endian directives to pack/unpack floats

- lib/protoboeuf/codegen.rb
- lib/protoboeuf/protobuf/stringvalue.rb
- test/fixtures/typed_test.correct.rb
- test/message_test.rb
The protobuf specs do require UTF-8 and that's what `google-protobuf` returns.
Otherwise returning binary encoded string migth work in most case and cause havoc when entering non-ASCII cases.
> Properly handle UTF-8 strings

- lib/protoboeuf/codegen.rb
- test/fixtures/typed_test.correct.rb
An optimization idea discussed with @maximecb.
Right now we reserve 10 bytes for submessages, then shift the submessage in the buffer to get rid of the unused ones.
This means we're always shifting the submessage unless it's gigantic enough to use 10 bytes to encode its length.
If instead we only reserve one byte, it allows us to not shift anything if the submessage is small enough for its length to only need one byte. So less work to do for submessages of less than 127B, as about as much work as before for bigger ones.
NB: I couldn't benchmark it yet, but my earlier profiles were showing ~10% of time spent in bytesplice, and most (not all) sub messages in the benchmark have a length that fit in one byte, so I'd expect a gain around ~8% or so.
cc @tenderworks
> Optimize `encode_submessage` to avoid shifting for small messages

- test/codegen_test.rb
I don't know if we want this but this is what I came up with for testing the `requires` change.
It just skips on the `protoc` version because it doesn't make sense there.
> Add a test for the "require unless self" logic

- lib/protoboeuf/codegen.rb
- test/codegen_test.rb
- test/fixtures/typed_test.correct.rb
We were encoding the number of items in a list, but the protobuf spec actually wants the number of bytes the list occupies.  This changes the codegen to encode lists similarly to submessages, speculating the length of the submessage will fit in one byte
> Fix list encoding

- lib/protoboeuf/codegen.rb
- test/codegen_test.rb
- test/fixtures/package_test.proto
- **Fix class name for type when pulling message**
- **Fix the class name for fields imported from protoc**
In the conformance tests we're getting code that looks like
```ruby
protobuf_test_messages.editions::TestAllTypesEdition2023::NestedEnum.lookup(
```
This fixes the class name to
```ruby
ProtobufTestMessages::Editions::TestAllTypesEdition2023::NestedEnum.lookup(
```
> Fix the class name for fields imported from protoc

- lib/protoboeuf/parser.rb
- test/parser_test.rb
The tests passed because NameError was being raised.
> Fix typos in Parser::Error name

- lib/protoboeuf/codegen.rb
- lib/protoboeuf/protobuf/descriptor.rb
- test/codegen_test.rb
We were removing underscores from enum names when we generate the class name. This restores the underscores (but only for enums)
> Enums with underscores should keep the underscore

- .github/workflows/ci.yml
- Rakefile
- bench/benchmark.rb
This converts the benchmark code to use the new AST format, also fixing the benchmarks.
`rake bench` works now:
```
/Users/aaron/.rubies/arm64/ruby-master/bin/ruby --yjit -I lib:bench/lib bench/benchmark.rb
total encoded size: 4715043 bytes
=== decode ===
ruby 3.4.0dev (2024-08-21T16:07:28Z master 53e3795379) +YJIT [arm64-darwin23]
Warming up --------------------------------------
upstream/jit    12.000 i/100ms
protoboeuf/jit     5.000 i/100ms
Calculating -------------------------------------
upstream/jit    120.726 (± 1.7%) i/s -    612.000 in   5.070227s
protoboeuf/jit     58.245 (± 0.0%) i/s -    295.000 in   5.065063s
Comparison:
upstream/interp:      120.6 i/s
upstream/jit:      120.7 i/s - same-ish: difference falls within error
protoboeuf/jit:       58.2 i/s - 2.07x  slower …
```
> Convert benchmark code to use new AST

- lib/protoboeuf/codegen.rb
- lib/protoboeuf/protobuf/descriptor.rb
- lib/protoboeuf/protobuf/field_mask.rb
- lib/protoboeuf/protobuf/struct.rb
- test/codegen_test.rb
- test/fixtures/test.proto
- test/parser_compatibility_test.rb
This fixes the case when a message has more than 15 fields.  If a field number is larger than 15, it must be encoded using multiple bytes.  This PR changes codegen so that if we need to decode multiple bytes (a varint) we will, but if the message is small enough (fewer than 16 fields) we'll only read one byte.
We also fixed a case where repeated fields need to check if they've consumed the entire message.  If so, they need to return.
This removes all `skips` from the test suite.
> Fix "too many fields" and "repeated fields" bugs

- lib/protoboeuf/codegen.rb
- lib/protoboeuf/protobuf/descriptor.rb
- lib/protoboeuf/protobuf/field_mask.rb
- lib/protoboeuf/protobuf/struct.rb
We need to check if we've consumed the message before reading the next tag, otherwise we'll get an exception (the benchmarks were raising exceptions).
> Check consumed length before reading next tag

- lib/protoboeuf/codegen.rb
- test/codegen_test.rb
- test/fixtures/typed_test.correct.rb
The conformance suite uses this.
> Define to_proto method for encoding a message instance

- lib/protoboeuf/codegen.rb
- lib/protoboeuf/protobuf/any.rb
- lib/protoboeuf/protobuf/boolvalue.rb
- lib/protoboeuf/protobuf/bytesvalue.rb
- lib/protoboeuf/protobuf/descriptor.rb
- lib/protoboeuf/protobuf/doublevalue.rb
- lib/protoboeuf/protobuf/duration.rb
- lib/protoboeuf/protobuf/field_mask.rb
- lib/protoboeuf/protobuf/floatvalue.rb
- lib/protoboeuf/protobuf/int32value.rb
- lib/protoboeuf/protobuf/int64value.rb
- lib/protoboeuf/protobuf/stringvalue.rb
- lib/protoboeuf/protobuf/struct.rb
- lib/protoboeuf/protobuf/timestamp.rb
- lib/protoboeuf/protobuf/uint32value.rb
- lib/protoboeuf/protobuf/uint64value.rb
- test/codegen_test.rb
- test/fixtures/typed_test.correct.rb
closes #140 
This changes to always do the full varint reading when pulling the tag.
A message (written by a newer version) may contain a tag number
higher than 15 (even if this older version has less than 15).
It may be possible to reintroduce this optimization
but the "if not found" code will have to determine if it needs
more bytes to finish the tag
before trying to pull the value.
This makes it correct; Later we can try to optimize it again if necessary.
> Ignore unknown fields when decoding

- .github/workflows/ci.yml
- lib/protoboeuf/codegen.rb
- lib/protoboeuf/protobuf/descriptor.rb
- test/codegen_test.rb
- test/well_known_types_test.rb
This fixes some issues in the conformance suite when the syntax is not proto3.
It's worth noting that our `descriptor.proto` is currently proto2, so it fixes some of the API for our generated well known type.
> Make the "optional field" checks consistent

- lib/protoboeuf/codegen.rb
- lib/protoboeuf/protobuf/any.rb
- lib/protoboeuf/protobuf/boolvalue.rb
- lib/protoboeuf/protobuf/bytesvalue.rb
- lib/protoboeuf/protobuf/descriptor.rb
- lib/protoboeuf/protobuf/doublevalue.rb
- lib/protoboeuf/protobuf/duration.rb
- lib/protoboeuf/protobuf/field_mask.rb
- lib/protoboeuf/protobuf/floatvalue.rb
- lib/protoboeuf/protobuf/int32value.rb
- lib/protoboeuf/protobuf/int64value.rb
- lib/protoboeuf/protobuf/stringvalue.rb
- lib/protoboeuf/protobuf/struct.rb
- lib/protoboeuf/protobuf/timestamp.rb
- lib/protoboeuf/protobuf/uint32value.rb
- lib/protoboeuf/protobuf/uint64value.rb
- test/codegen_test.rb
- test/fixtures/typed_test.correct.rb
The conformance suite attempts to decode a lot of empty messages.
> Check if there is buffer left before reading first tag

- bench/benchmark.rb
- lib/protoboeuf/codegen.rb
Final version of: https://github.com/Shopify/protoboeuf/pull/116
Ref: https://bugs.ruby-lang.org/issues/20594
This isn't yet as fast as the prototype because the final method was merged as `append_as_bytes` with variadic and Integer support so I haven't implemented a YJIT acceleration yet.
But since we can now consider the interface stable, we can merge.
> Use `String#append_as_bytes` if available

- lib/protoboeuf/codegen.rb
- test/codegen_test.rb
The limit was 62.
The conformance suite needs 63.
If we want to keep the mask as a simple fixnum in ruby it would need to be 61.
This is the code being generated now, the `field_name17` is number 62 (you can see how the bitmask gets longer):
```
def has_field__name15?
(@_bitmask & 0x4000000000000000) == 0x4000000000000000
end
def has_field__Name16?
(@_bitmask & 0x8000000000000000) == 0x8000000000000000
end
def has_field_name17__?
(@_bitmask & 0x10000000000000000) == 0x10000000000000000
end
```
Looking at it through ruby's eyes:
```
irb /main:036:0:> sprintf "%16x", Fiddle.dlwrap(1 << 60)
=> "2000000000000001"
irb /main:037:0:> sprintf "%16x", Fiddle.dlwrap(1 << 61)
=> "4000000000000001"
irb /main:038:0:> sprintf "%16x", Fiddle.dlwrap(1 << 62)
=> "    7f0e32c2a280"
irb /main:039:0:> …
```
> Remove artificial limit on optional field count

- lib/protoboeuf/codegen.rb
- lib/protoboeuf/protobuf/any.rb
- lib/protoboeuf/protobuf/boolvalue.rb
- lib/protoboeuf/protobuf/bytesvalue.rb
- lib/protoboeuf/protobuf/descriptor.rb
- lib/protoboeuf/protobuf/doublevalue.rb
- lib/protoboeuf/protobuf/duration.rb
- lib/protoboeuf/protobuf/field_mask.rb
- lib/protoboeuf/protobuf/floatvalue.rb
- lib/protoboeuf/protobuf/int32value.rb
- lib/protoboeuf/protobuf/int64value.rb
- lib/protoboeuf/protobuf/stringvalue.rb
- lib/protoboeuf/protobuf/struct.rb
- lib/protoboeuf/protobuf/timestamp.rb
- lib/protoboeuf/protobuf/uint32value.rb
- lib/protoboeuf/protobuf/uint64value.rb
- test/codegen_compatibility_test.rb
- test/codegen_test.rb
- test/fixtures/typed_test.correct.rb
When a message is decoded that has fields the current module doesn't utilize, just append them to the end of the message when re-encoding a message from this instance.
The conformance suite tests for this.
> Include unknown fields from decoding into output when re-encoding

- lib/protoboeuf/codegen.rb
- lib/protoboeuf/google/api/field_behavior.rb
- lib/protoboeuf/google/protobuf/descriptor.rb
- lib/protoboeuf/google/protobuf/struct.rb
- test/codegen_test.rb
- test/fixtures/typed_test.correct.rb
I ran across an issue when working with an `enum` definition with thousands of values.  `SyntaxTree` ran into a "nesting too deep" error when attempting to format the code:
```
1) Error:
ProtoBoeuf::CodeGenTest#test_big_enum:
SyntaxTree::Parser::ParseError: nesting too deep
/Users/dave/.gem/ruby/3.3.4/gems/syntax_tree-6.2.0/lib/syntax_tree/parser.rb:2864:in `on_parse_error'
/Users/dave/.gem/ruby/3.3.4/gems/syntax_tree-6.2.0/lib/syntax_tree.rb:124:in `parse'
/Users/dave/.gem/ruby/3.3.4/gems/syntax_tree-6.2.0/lib/syntax_tree.rb:124:in `parse'
/Users/dave/.gem/ruby/3.3.4/gems/syntax_tree-6.2.0/lib/syntax_tree.rb:68:in `format'
lib/protoboeuf/codegen.rb:1723:in `block in to_ruby'
lib/protoboeuf/codegen.rb:1703:in `each'
lib/protoboeuf/codegen.rb:1703:in `to_ruby'
test/codegen_test.rb:12:in …
```
> Tweak generated class methods .lookup and .resolve for enums to prevent StackError when formatting
